menus: 
    - main:
            -   
                label: Home
                path: /
            -   
                label: Spotify
                path: /spotify
            -   
                label: CV
                path: /cv