path: /articles/playlists
title: Playlists
template: articles/playlists
slug: playlists
description: |
  I put a lot of effort into my spotify playlists, I generally creat new ones on a monthly basis. I have recorded them here, mainly because the Spotify library feature doesn't really cut and I generally forget what I've put together. 
date: "2020-10-15"
controller: ["Articles"]
playlists: 
    themed:
        - id: '5CgYoF9DYeNeNnGWSdPNma'
          label: ''  
          description: ''
    eclectic:
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''          
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''  
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''  
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''  
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: '' 
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''                      
                                              