path: /playlists
title: Playlists
template: playlists
slug: playlists
header: |
    # Playlists
playlists: 
    themed:
        - id: '5CgYoF9DYeNeNnGWSdPNma'
          label: ''  
          description: ''
    eclectic:
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''          
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''  
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''  
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''  
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: '' 
        - id: '4PwmrQtSko5E2k8timUF5k'
          label: '' 
          description: ''                      
                                              